name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm run app:dist -- --mac
      - uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*.dmg
          